### ISSUE TITLE
Modifying milestones causes duplicate lowerings

### ISSUE THREAD

**Issue by rgov** [WHOIGit/ndsf-sealog-client#34] opened 2022-11-08 18:24 UTC
e.g., 2022 -> TN406 -> J2-1438

**Comment by rgov** [comment] 2022-11-13 20:12
Note that `set_lowering_stats_modal.js` and `update_lowering_stats_form.js` both exist.

**Comment by mcschwartzman** [comment] 2023-01-09 20:27
Not able to reproduce this locally, was this merged but not deployed?

**Comment by rgov** [comment] 2023-01-09 20:34
I didn’t change anything I don’t think. What I suspect is happening is that rather than submitting an update to an existing entry by ID it is creating a new document with a new ID.

**Comment by mcschwartzman** [comment] 2023-01-09 20:43
It's definitely DID do that, as can be seen from these entries on the prod DB:

```
[{
        "lowering_id": "J2-1438",
        "id": "62e1e5ec623020001c6299ab"
    },
    {
        "lowering_id": "J2-1438",
        "id": "634ede4e8737f7001edb83e1"
    },
    {
        "lowering_id": "J2-1438",
        "id": "634edeab8737f7001edb83e2"
    }]
```

NOTE: the delete api also deletes associated lowering files so we should NOT use that to delete

**Comment by mcschwartzman** [comment] 2023-01-11 20:37
Note: This is no longer happening in Prod. Root cause unclear.

**Comment by mcschwartzman** [comment] 2023-02-21 18:03
Closing due to inability to replicate. Will reopen if it happens again.

**Closed by mcschwartzman** 2023-02-21 18:03 UTC
